//! Acceptance: "same fixture inputs -> byte-identical markdown across
//! two renders" — `canon report --check`'s entire drift-gate contract
//! depends on this holding (design D2).

mod support;

use canon_report::{report, ReportInputs};

#[test]
fn rendering_the_same_fixture_twice_is_byte_identical() {
    if !support::duckdb_available() {
        eprintln!("skipping: `duckdb` CLI not found on PATH");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let roots = support::corpus::build(dir.path());
    let inputs = ReportInputs::new(dir.path(), roots);

    let first = report(&inputs).unwrap();
    let second = report(&inputs).unwrap();

    assert_eq!(first, second, "two renders of the identical fixture corpus must be byte-identical");
    assert!(!first.contains("generated_at"), "the report must be TIMESTAMP-FREE (decision 11)");
    assert!(first.starts_with("# canon report\n"));
    assert!(first.contains("GENERATED by `canon report`"), "must carry the DO-NOT-EDIT generated header (D16)");
}

#[test]
fn digest_header_reflects_the_repo_state_the_corpus_was_built_at() {
    if !support::duckdb_available() {
        eprintln!("skipping: `duckdb` CLI not found on PATH");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let roots = support::corpus::build(dir.path());
    let inputs = ReportInputs::new(dir.path(), roots);

    let content = report(&inputs).unwrap();
    // No `canon/policy.yaml` in this fixture dir — the policy digest
    // degrades to its documented placeholder, never a panic or an
    // `Err`.
    assert!(content.contains("| policy | `—` |"));
    // Corpus/ledger both have real content -> a real 12-hex digest, not
    // the empty-corpus placeholder.
    assert!(!content.contains("corpus (change/task/scenario) | `—`"));
    assert!(!content.contains("ledger head (evidence/review/divergence) | `—`"));
}
