//! Markdown rendering: [`render`] assembles the digest header + six
//! mart panels into one byte-stable markdown document — "generated,
//! never hand-edited" (design D16), a leading `<!-- GENERATED … DO NOT
//! EDIT -->` comment (task 1.3), and the [`crate::digest::DigestHeader`]
//! table (TIMESTAMP-FREE, decision 11 — no `generated_at` field
//! anywhere below). Every panel section is produced by straight,
//! deterministic string formatting over already-sorted mart rows
//! (`crate::marts`'s `ORDER BY` clauses) — no `HashMap`/wall-clock/
//! random-order input anywhere in this module, the byte-stability
//! property `crate::check` relies on.

use canon_model::envelope::RecordKind;

use crate::digest::DigestHeader;
use crate::marts::MartResult;
use crate::tier_boundary;

/// The path a rendered report is conventionally written to when a
/// caller (this crate's own `[[bin]]`, or the future `canon-cli`
/// `canon report` arm, part2) does not have a `canon.yaml`-configured
/// override — mirrors `canon-learn`'s own `.canon/`-prefixed default
/// convention (`DEFAULT_LEARN_ROOT`, `DEFAULT_STRATEGIES_ROOT`).
pub const DEFAULT_REPORT_PATH: &str = canon_model::paths::REPORT_FILE;

fn cell(row: &crate::query::Row, column: &str) -> String {
    match row.get(column) {
        None | Some(serde_json::Value::Null) => "—".to_string(),
        Some(serde_json::Value::Bool(b)) => if *b { "✓" } else { "·" }.to_string(),
        Some(serde_json::Value::String(s)) => s.clone(),
        Some(other) => other.to_string(),
    }
}

fn render_table(out: &mut String, mart: &MartResult) {
    if mart.rows.is_empty() {
        out.push_str("_No rows._\n\n");
        return;
    }
    out.push('|');
    for column in mart.columns {
        out.push_str(&format!(" {column} |"));
    }
    out.push('\n');
    out.push('|');
    for _ in mart.columns {
        out.push_str("---|");
    }
    out.push('\n');
    for row in &mart.rows {
        out.push('|');
        for column in mart.columns {
            out.push_str(&format!(" {} |", cell(row, column)));
        }
        out.push('\n');
    }
    out.push('\n');
}

/// The seven panels this report renders, in design D5's own declared
/// order, with s24's `scope_status` and s36's `subjects` appended last.
pub struct ReportMarts {
    pub trust_matrix: MartResult,
    pub session_costs: MartResult,
    pub role_memory: MartResult,
    pub flywheel_funnel: MartResult,
    pub review_burndown: MartResult,
    pub scope_status: MartResult,
    pub subjects: MartResult,
}

/// Renders the full report markdown. Pure formatting over already-
/// computed inputs (`digest`, `marts`, `kinds_not_read_directly`) —
/// deterministic, so calling this twice with identical inputs produces
/// byte-identical output (the property `crate::check::check`'s drift
/// gate and this crate's own byte-stability test both exercise).
/// `kinds_not_read_directly` is config-derived
/// (`crate::tier_boundary::kinds_not_read_directly`, `canon.yaml`'s
/// static `routing`/`tiers` tables), never a live, non-directly-
/// readable-backend read (s28 design D2) — an empty slice renders NO
/// `## Kinds not read directly` section at all (design D2), so every
/// fixture whose `canon.yaml` routes nothing to a not-directly-read
/// backend renders byte-identically to before this parameter existed.
pub fn render(digest: &DigestHeader, marts: &ReportMarts, kinds_not_read_directly: &[RecordKind]) -> String {
    let mut out = String::new();
    out.push_str("# canon report\n\n");
    out.push_str("<!-- GENERATED by `canon report` (design doc D16/S9 decision 11). DO NOT EDIT.\n");
    out.push_str("     Run `canon report --check` at the same inputs to verify freshness; a mismatch is drift, not a merge conflict to resolve by hand. -->\n\n");

    out.push_str("## Inputs (digest)\n\n");
    out.push_str("| input | digest |\n|---|---|\n");
    out.push_str(&format!("| corpus (change/task/scenario) | `{}` |\n", digest.corpus_hash));
    out.push_str(&format!("| policy | `{}` |\n", digest.policy_hash));
    out.push_str(&format!("| ledger head (evidence/review/divergence) | `{}` |\n", digest.ledger_hash));
    out.push('\n');

    if let Some(note) = tier_boundary::render_note(kinds_not_read_directly) {
        out.push_str(&note);
    }
    out.push_str("## Trust matrix\n\n");
    out.push_str("Change/task coverage × green × who (`mart_trust_matrix`).\n\n");
    render_table(&mut out, &marts.trust_matrix);

    out.push_str("## Session costs\n\n");
    out.push_str("Token/cost by role/repo/session (`mart_session_costs`).\n\n");
    render_table(&mut out, &marts.session_costs);

    out.push_str("## Role memory\n\n");
    out.push_str("Strategies, hit rate, effect per role namespace (`mart_role_memory`).\n\n");
    render_table(&mut out, &marts.role_memory);

    out.push_str("## Flywheel funnel\n\n");
    out.push_str("Verdicts → distilled → retrieved → applied (`mart_flywheel_funnel`).\n\n");
    render_table(&mut out, &marts.flywheel_funnel);

    out.push_str("## Review burn-down\n\n");
    out.push_str("Review-feedback burn-down over time (`mart_review_burndown`).\n\n");
    render_table(&mut out, &marts.review_burndown);

    out.push_str("## Scope status\n\n");
    out.push_str("Task done × evidence-verified × spec-covered, per declared scenario ref (`mart_scope_status`).\n\n");
    render_table(&mut out, &marts.scope_status);

    out.push_str("## Subjects\n\n");
    out.push_str("Per-domain subject rollup: status × scenario coverage (`mart_subjects`).\n\n");
    render_table(&mut out, &marts.subjects);

    out
}
