//! Generated join-spine documentation (S1 spec `join-spine`, design D3,
//! task 2.3). [`render`] builds the eight-key Markdown table straight
//! from each join-key newtype's `GRAMMAR`/`JOINS` associated constants
//! (`crate::ids`) — the exact same literals that produced those types'
//! own rustdoc comments (see `crate::ids`'s module doc), so this doc can
//! never silently drift from the types that implement it.

use crate::ids::{ChangeId, HandoffId, RegimeKey, RunId, ScenarioId, Sha, SubjectId, TaskId};

/// One join-spine table row.
pub struct JoinSpineRow {
    pub key: &'static str,
    pub grammar: &'static str,
    pub joins: &'static str,
}

/// The nine join-spine keys, in the design doc's own table order.
/// `sha` / `pr` is one combined row (design D3's table) sourced from
/// [`Sha`]'s constants — [`crate::ids::PrNumber`] documents its own half
/// of that row separately in its own rustdoc, since it is not a
/// `String`-newtype `join_key_newtype!` participant. `subject_id` (s36)
/// is the ninth key.
pub fn rows() -> Vec<JoinSpineRow> {
    vec![
        JoinSpineRow { key: "change_id", grammar: ChangeId::GRAMMAR, joins: ChangeId::JOINS },
        JoinSpineRow { key: "task_id", grammar: TaskId::GRAMMAR, joins: TaskId::JOINS },
        JoinSpineRow { key: "scenario_id", grammar: ScenarioId::GRAMMAR, joins: ScenarioId::JOINS },
        JoinSpineRow {
            key: "session_id",
            grammar: crate::ids::SessionId::GRAMMAR,
            joins: crate::ids::SessionId::JOINS,
        },
        JoinSpineRow { key: "run_id", grammar: RunId::GRAMMAR, joins: RunId::JOINS },
        JoinSpineRow { key: "handoff_id", grammar: HandoffId::GRAMMAR, joins: HandoffId::JOINS },
        JoinSpineRow { key: "sha` / `pr", grammar: Sha::GRAMMAR, joins: Sha::JOINS },
        JoinSpineRow { key: "regime_key", grammar: RegimeKey::GRAMMAR, joins: RegimeKey::JOINS },
        JoinSpineRow { key: "subject_id", grammar: SubjectId::GRAMMAR, joins: SubjectId::JOINS },
    ]
}

/// Render `rows()` as the committed `JOIN_SPINE.md` document.
pub fn render() -> String {
    let mut out = String::new();
    out.push_str("<!-- GENERATED by `cargo xtask write` (crates/canon-model/src/join_spine_doc.rs). -->\n");
    out.push_str("<!-- Do not hand-edit — edit the GRAMMAR/JOINS on the join-key newtypes in `src/ids.rs` instead. -->\n\n");
    out.push_str("# canon join spine\n\n");
    out.push_str("The nine keys that join every canon-model record kind together (S1 design D3, extended by s36).\n\n");
    out.push_str("| Key | Grammar | Joins |\n");
    out.push_str("|---|---|---|\n");
    for row in rows() {
        out.push_str(&format!("| `{}` | {} | {} |\n", row.key, row.grammar, row.joins));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exactly_nine_rows() {
        assert_eq!(rows().len(), 9);
    }

    #[test]
    fn render_contains_every_key() {
        let doc = render();
        for row in rows() {
            let bare_key = row.key.split('`').next().unwrap();
            assert!(doc.contains(bare_key), "generated doc missing key `{bare_key}`");
        }
    }
}
